Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/08/2020
Var
n, cont , n2 : inteiro


Inicio

 cont :=0
 n:=7

 enquanto (n2<=1000) faca
    cont <- cont + 1
     n2<- cont * n
       escreval (n," x ", cont," = ",n2)
fimenquanto
Fimalgoritmo