Algoritmo "semnome"

var
   n: vetor [1..3] de inteiro
   contador : inteiro
   resultado : inteiro
Inicio

   para contador de 1 ate 2 passo 1  faca
      escreval ("qual o numero ?")
      leia (N[contador])
    resultado<- n[1]+n[2]
      n[3] <- (n[1]+n[2])*2

   fimpara
   escreval ("a soma dos dois numeros é:",resultado)
   escreval ("o resultado em dobro dos numeros é:", n[3])

Fimalgoritmo