Algoritmo "semnome"

Var

   cont,n,res: inteiro

Inicio

   escreval ("aqui estao todos os multiplos de 7 que o resultado щ inferior a 1000")
   escreval ("ииииииииииииииииииииииииииииииииииииииииииииииииииииииииииииииии")
   cont := 0
   n := 7
   enquanto (res<994) faca
      cont <- cont + 1
      res <- n * cont
      escreval (n," X ",cont," = ",res)
   fimenquanto
Fimalgoritmo