Algoritmo "semnome"

Var

   c: real
   f: inteiro
Inicio

   escreval ("converta graus Fahrenheit em graus celsius")
   escreval ("ииииииииииииииииииииииииииииииииииииииииииииии")
   escreva ("digite quantos graus esta: ")
   leia (f)
 c <- (f - 32)*(5/9)
   escreval ("a coversao de graus foi feita")
   escreval ("de",f," graus Fahrenheit foi para",c," graus celsius")


Fimalgoritmo